name: Check Release
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  check_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [check_release, link_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Upgrade packaging dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel --user

      - name: Install Dependencies
        run: |
          pip install -e .

      - name: Check Release
        if: ${{ matrix.group == 'check_release' }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Link Check
        if: ${{ matrix.group == 'link_check' }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-links@v1

      - name: Upload Distributions
        if: ${{ matrix.group == 'check_release' }}
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlab-lsp-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
